[window]
dimensions = { columns = 64, lines = 24 }
padding = { x = 0, y = 0 }

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Block", blinking = "Always" }
blink_interval = 500

[font]
size = 11
normal = { family = "Terminus" }
