[window]
dimensions = { columns = 52, lines = 26 }
padding = { x = 8, y = 8 }

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Block", blinking = "Always" }
blink_interval = 500

[font]
size = 14
normal = { family = "Terminus", style = "Regular" }
bold = { style = "Regular" }
