#! /bin/sh
. "$HOME/bin/colors"

killall sxhkd; sxhkd &
picom &
hsetroot -solid $color0 &
xsetroot -cursor_name left_ptr &

bspc config normal_border_color   $color2
bspc config active_border_color   $color1
bspc config focused_border_color  $color1
bspc config presel_feedback_color $color2
bspc config border_width          1
bspc config window_gap            8
bspc config split_ratio           1
bspc config borderless_monocle    true
bspc config gapless_monocle       true

bspc monitor -d 1 2 3 4 5

bspc rule -a '*'     state=floating
bspc rule -a Neko    manage=off
