#! /bin/sh
. ~/.theme
envsubst < ~/.Xresources > /tmp/Xresources &
xrdb /tmp/Xresources &
killall sxhkd; sxhkd &
picom &
hsetroot -solid $C0 &
xsetroot -cursor_name left_ptr &

bspc config normal_border_color   $C2
bspc config active_border_color   $C1
bspc config focused_border_color  $C1
bspc config presel_feedback_color $C2
bspc config border_width          1
bspc config window_gap            8
bspc config top_padding           96
bspc config bottom_padding        96
bspc config left_padding          96
bspc config right_padding         96
bspc config split_ratio           1
bspc config borderless_monocle    false
bspc config gapless_monocle       false

bspc monitor -d 1 2 3 4 5

bspc rule -a '*'     state=floating
bspc rule -a Neko    manage=off
