#! /bin/sh

. "${HOME}/.cache/wal/colors.sh"

pgrep -x sxhkd > /dev/null || sxhkd &
picom &
hsetroot -solid $color0 &
xsetroot -cursor_name left_ptr &
killall polybar; wait 0.1; polybar &

bspc config normal_border_color "$color8"
bspc config active_border_color "$color7"
bspc config focused_border_color "$color7"
bspc config presel_feedback_color "$color8"

bspc monitor -d 1 2 3 4 5

bspc config border_width        2
bspc config window_gap          32
"""
bspc config left_padding        2
bspc config right_padding       2
bspc config top_padding         40
bspc config bottom_padding      2
"""

bspc config split_ratio         1
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc rule -a '*'                state=floating
bspc rule -a Neko               manage=off
